name: gptme-bot

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      # needed to run the action in the same repo
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run gptme-bot action
        uses: ./.github/actions/bot
        with:
          model: 'anthropic/claude-3-5-sonnet-20240620'
          # model: 'openai/gpt-4o'
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allowlist: "Sunwood-ai-labs"
